[project]
name = "livegepsimootori"
version = "0.1.0"
requires-python = ">=3.14"


[tool.black]
target-version = ['py314']
line-length = 88

[tool.isort]
profile = "black"

[tool.djlint]
ignore="H021"

[tool.coverage.run]
omit = [
  "invitations/admin.py",
  "routechoices/core/admin.py",
  "routechoices/lib/other_gps_services/*.py",
]
