version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
  codecov: codecov/codecov@3.2.5

commands:
  prepare-docker:
    steps:
      - run:
          name: Local certificates setup
          command: |
            ./gen-local-certs.sh
            chmod -R 755 ./letsencrypt/live/routechoices.dev/

      - run:
          name: DNS overrides
          command: |
            echo "DNSStubListener=no" | sudo tee -a /etc/systemd/resolved.conf
            sudo systemctl restart systemd-resolved
            sudo apt-get update
            sudo apt-get install -y dnsmasq
            echo -e "bind-interfaces\nlisten-address=127.0.0.1\naddress=/routechoices.dev/127.0.0.1\naddress=/.routechoices.dev/127.0.0.1" | sudo tee /etc/dnsmasq.conf
            sudo systemctl restart dnsmasq
            cat <(echo "nameserver 127.0.0.1") /etc/resolv.conf | sudo tee /tmp/resolv.conf
            sudo rm /etc/resolv.conf
            sudo mv /tmp/resolv.conf /etc/resolv.conf
            sudo systemctl restart systemd-resolved

      - run:
          name: Create media directories
          command: mkdir -p media/s3/routechoices media/iam media/versioning media/sidecar

      - run:
          name: Setup environment
          command: |
            mv ./.env.dev ./.env
            echo "SECURE_SSL_REDIRECT = False" > ./routechoices/settings_overrides.py
            echo "DEBUG = False" >> ./routechoices/settings_overrides.py

      - run:
          name: Start application
          command: |
            ./dc up -d
            ./da migrate
            ./da collectstatic
            ./da compress
            ./dc restart nginx

  wait-app-online:
    steps:
      - run:
          name: Wait for the site to be online
          command: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' https://www.routechoices.dev/)" != "200" ]]; do sleep 5; done' || false

jobs:
  python-tests:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - checkout
      - prepare-docker
      - run:
          name: Restart django
          command: ./dc restart django
      - wait-app-online
      - run:
          name: Run tests
          command: ./test
      - codecov/upload:
          file: coverage.xml
          flags: unittests

  e2e-tests:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libgbm-dev
      - browser-tools/install-chrome
      - run:
          name: Install NodeJS and Cypress
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v25 && nvm use v25 && nvm alias default v25
            node -v
            npm install cypress
      - prepare-docker
      - run:
          name: Restart application with coverage enabled
          command: |
            ./dc stop django
            ./dc up -d
          environment:
            WSGI_FILE: wsgi-with-cov
            NUM_PROCESSES: 1
      - wait-app-online
      - run:
          name: Run tests
          command: TZ=Europe/Helsinki node_modules/cypress/bin/cypress run --browser chrome
      - run:
          name: Collect coverage
          command: |
            docker kill --signal=HUP rc_django
            sleep 5
            ./dc exec django coverage xml
      - codecov/upload:
         file: coverage.xml
         flags: e2e
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  build-docker:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Connect account
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build docker image
          command: |
            docker build --progress plain --platform linux/amd64 --push -t rphlo/routechoices-dev-server:latest -f docker/django.dockerfile .

workflows:
  version: 2
  run_tests:
    jobs:
      - python-tests
      - e2e-tests
  build_image:
    jobs:
      - build-docker:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
