# Generated by Django 5.2.7 on 2025-11-15 15:23

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_alter_competitor_start_time_alter_event_end_date_and_more"),
    ]

    operations = []
