# Generated by Django 5.2.8 on 2025-12-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_club_is_personal_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_personal_page',
        ),
    ]
