# Generated by Django 5.2.8 on 2025-12-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_remove_spotdevice_device_delete_spotfeed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotdevice",
            name="device",
        ),
        migrations.DeleteModel(
            name="SpotFeed",
        ),
        migrations.DeleteModel(
            name="SpotDevice",
        ),
    ]
