# Generated by Django 6.0 on 2025-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_remove_spotdevice_device_delete_spotfeed_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_list_frontpage_idx",
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="core_event_listing_idx",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="on_events_page",
            new_name="featured",
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("featured"),
                models.F("end_date"),
                models.F("event_set_id"),
                name="core_event_list_frontpage_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.F("privacy"),
                models.F("featured"),
                models.F("end_date"),
                name="core_event_listing_idx",
            ),
        ),
    ]
