# Generated by Django 6.0 on 2025-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_remove_event_core_event_list_frontpage_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
    ]
