# Generated by Django 6.0 on 2025-12-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_alter_event_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="o_club",
        ),
    ]
