# Generated by Django 5.2.11 on 2026-02-24 08:14

import routechoices.core.models
import routechoices.lib.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_remove_club_o_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="forbid_invite_request",
            field=models.BooleanField(
                default=False,
                verbose_name="Prevent external users from requesting admin rights",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="geojson_layer",
            field=models.FileField(
                blank=True,
                help_text='A <a href="//www.routechoices.com/guide/geojson" target="_blank" rel="nofollow noopener">GeoJSON CSS</a> file.',
                null=True,
                storage=routechoices.lib.storages.OverwriteImageStorage(
                    aws_s3_bucket_name="routechoices"
                ),
                upload_to=routechoices.core.models.geojson_upload_path,
                verbose_name="GeoJSON Layer",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="tail_length",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Default tail length when a user opens the event. Can be overridden by the viewers in the event page settings tab.",
                verbose_name="Tail length (seconds)",
            ),
        ),
    ]
