# Generated by Django 5.2.11 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_alter_club_forbid_invite_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="acceptable_tags",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Registration accepted categories",
            ),
        ),
    ]
