# Generated by Django 5.2.11 on 2026-04-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_event_acceptable_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicearchivereference",
            options={"ordering": ["-creation_date"]},
        ),
    ]
