# Generated by Django 5.2.11 on 2026-04-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_alter_devicearchivereference_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frontpagefeedback",
            options={"verbose_name": "feedback", "verbose_name_plural": "feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="imeidevice",
            options={
                "ordering": ["imei"],
                "verbose_name": "IMEI",
                "verbose_name_plural": "IMEIs",
            },
        ),
    ]
