# Generated by Django 5.2.11 on 2026-04-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_alter_frontpagefeedback_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tcpdevicecommand",
            options={
                "ordering": ["-modification_date"],
                "verbose_name": "TCP command",
                "verbose_name_plural": "TCP commands",
            },
        ),
    ]
