# Generated by Django 5.2.13 on 2026-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_alter_tcpdevicecommand_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("preview", "Pre-Event"),
                    ("live", "Live"),
                    ("replay", "Replay"),
                ],
                default="live",
                help_text="Pre-Event: Maps are visible from event creation date | Live: Maps are visible from event start date | Replay: Maps are visible from event end date",
                max_length=8,
            ),
        ),
    ]
