# Generated by Django 5.2.13 on 2026-05-09 09:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_event_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["aid"],
                "verbose_name": "GPS device",
                "verbose_name_plural": "GPS devices",
            },
        ),
        migrations.AlterModelOptions(
            name="eventset",
            options={
                "ordering": ["-creation_date", "name"],
                "verbose_name": "Event bundle",
            },
        ),
        migrations.AlterField(
            model_name="club",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="virtual",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="acceptable_tags",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Participants accepted categories upon registration",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="allow_route_upload",
            field=models.BooleanField(
                default=False,
                help_text="Allows the registered participants to upload their GPS file.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.club",
                verbose_name="Club",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_set",
            field=models.ForeignKey(
                blank=True,
                help_text="Event within the same bundle are listed together on our pages.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="core.eventset",
                verbose_name="bundle",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="open_registration",
            field=models.BooleanField(
                default=False,
                help_text="Allow anyone to register themselves as participants of this event.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Published"),
                    ("secret", "Secret"),
                    ("private", "Staff Only"),
                ],
                default="public",
                help_text="Controls how we show the event, if it is published on our pages, or if it is kept secret while accessible to all, or if it is accessible only to its authenticated club staff members.",
                max_length=8,
                verbose_name="Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="send_interval",
            field=models.PositiveIntegerField(
                default=5,
                help_text="If using live GPS trackers, enter here the upload interval setting of your devices, when using one of the official app, leave the value at 5 seconds",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Live upload interval (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="tail_length",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Set the length of the tails displayed on the map when user open the event page.",
                verbose_name="Tail length (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("live", "From start date"),
                    ("replay", "After completion"),
                    ("preview", "Always available"),
                ],
                default="live",
                help_text="Controls when this event becomes visible to users.",
                max_length=8,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_sets",
                to="core.club",
                verbose_name="Club",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="create_page",
            field=models.BooleanField(
                default=False,
                help_text="Creates a page with all the events of the bundle listed",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text displayed on the page, use markdown formatting",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(
                default=False, help_text="Controls if the page lists the secret events"
            ),
        ),
        migrations.AlterField(
            model_name="map",
            name="club",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maps",
                to="core.club",
            ),
        ),
    ]
