# Generated by Django 5.2.13 on 2026-05-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_alter_device_options_alter_eventset_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceclubownership",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_owner",
                to="core.club",
            ),
        ),
        migrations.AlterField(
            model_name="deviceclubownership",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_ownerships",
                to="core.device",
                verbose_name="Tracker",
            ),
        ),
        migrations.AlterField(
            model_name="eventset",
            name="list_secret_events",
            field=models.BooleanField(default=False),
        ),
    ]
