# Generated by Django 5.2.13 on 2026-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_alter_deviceclubownership_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(verbose_name="Closing Date"),
        ),
    ]
