# Generated by Django 5.2.14 on 2026-05-22 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_alter_event_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="map_tags",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Categories that uses the main map",
            ),
        ),
        migrations.AddField(
            model_name="mapassignation",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Categories that uses this map",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_main_map",
                to="core.map",
                verbose_name="Default map",
            ),
        ),
    ]
