# Generated by Django 5.2.14 on 2026-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_event_map_tags_mapassignation_tags_alter_event_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="map_tags",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Default map categories",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="map_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Leave blank if not using extra maps",
                max_length=255,
                verbose_name="Default map title",
            ),
        ),
    ]
