# Generated by Django 5.2.14 on 2026-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_alter_tags_separator"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=128
            ),
        ),
        migrations.AddField(
            model_name="eventset",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, default="", editable=False, max_length=128
            ),
        ),
    ]
