# Generated by Django 5.2.17 on 2026-09-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_deviceclubownership_core_device_club_id_76981e_idx"),
        ("core", "0122_merge_20260909_1432"),
    ]

    operations = []
